# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Issue
        env:
          JOB_CONTEXT: ${{ toJSON(github.event.issue) }}
        run: echo "$JOB_CONTEXT"
      - name: build result to slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Geerio CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
#       - name: slack-send
#         # You may pin to the exact commit or the version.
#         # uses: slackapi/slack-github-action@410ae57cff5c6b682b106440be0e6c7eb8c98c9d
#         id: slack
#         uses: slackapi/slack-github-action@v1.16.0
#         with:
#           payload: "{\"key\":\"value\",\"foo\":\"bar\"}"
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         with:
#           # Slack channel ID where message will be posted. Needed if using bot token
#           channel-id: 'C02NF1Q4HDJ'
#           # Message to post into Slack. Needed if using bot token
#           slack-message: 'Test입니다. 반갑습니다!'
#           #JSON payload to send to Slack if webhook route. If not supplied, json from GitHub event will be sent instead
#           payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"You have a new request: \"}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Type:* Computer (laptop)\"},{\"type\":\"mrkdwn\",\"text\":\"*When:* Submitted Aut 10\"}]}]}"

      # Runs a single command using the runners shell
#       - name: Deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.AWS_HOST }}
#           username: ${{ secrets.AWS_USERNAME }}
#           key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
#           port: ${{ secrets.AWS_PORT }}
#           script: |
#             ${{ secrets.TEST_SCRIPT}}
